#!/bin/bash

#
# Build script (with run & check support) similar to cargo
#

cd $(dirname ${BASH_SOURCE})

set -eu

script_name=$(basename $0)
mode=help
profile=${profile-debug}
compiler=${compiler-clang21}
run_args=()
args=("$@")
PIPE_COLORPATH=""
if [[ -e /usr/bin/colorpath ]]; then PIPE_COLORPATH="| /usr/bin/colorpath"; fi

target=${target-}
INSTALL_DIR=${INSTALL_DIR-./install}

start_time=$(date +%s)
do_configure=0
flags=""
cfg_flags="-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}"
test_flags=""
git_cached_only=0
nargs=$(($# - 1))
i=0
while [[ $i -le $nargs ]]; do
    arg="${args[$i]}"
    if [[ $arg == "-r" ]]; then
        profile=release
    elif [[ $arg == "-v" ]]; then
        flags="$flags $arg"
    elif [[ ${arg:0:2} == "-D" ]]; then
        if [[ $arg == "-D" ]]; then
            i=$(($i + 1))
            cfg_flags="$cfg_flags -D ${args[$i]}"
        else
            cfg_flags="$cfg_flags $arg"
        fi
    elif [[ ${arg:0:11} == "--compiler=" ]]; then
        compiler=("${arg:11}")
    elif [[ ${arg:0:10} == "--profile=" ]]; then
        profile=("${arg:10}")
    elif [[ ${arg:0:11} == "--gcc" ]]; then
        compiler=("gcc")
    elif [[ $arg == "--cfg" || $arg == "--configure" ]]; then
        do_configure=1
    elif [[ $arg == "cfg" || $arg == "configure" ]]; then
        mode=configure
        do_configure=1
    elif [[ $arg == "b" || $arg == "build" ]]; then
        mode=build
    elif [[ $arg == "r" || $arg == "run" ]]; then
        mode=run
    elif [[ $arg == "install" ]]; then
        mode=install
    elif [[ $arg == "c" || $arg == "check" ]]; then
        mode=check
    elif [[ $arg == "t" || $arg == "test" ]]; then
        mode=test
    elif [[ ${arg:0:10} == "--sanitize" ]]; then
        profile=${profile}.sanitize
    elif [[ ${arg} == "--git-cached" ]]; then
        git_cached_only=1
    elif [[ $arg == "--" ]]; then
        shift $i
        shift 1
        run_args=($@)
        break
    else
        # Unknown arg
        if [[ "$mode" == "test" ]]; then
            if [[ ${arg:0:1} == "-" ]]; then
                echo "Unsupported test flag $arg"
            fi
            test_flags="$test_flags $arg"
        elif [[ $target == "" ]]; then
            target="$arg"
        elif [[ "$mode" == "run" ]]; then
            run_args+=("$arg")
        else
            echo "Unknown arg $arg"
        fi
    fi
    i=$(($i + 1))
done

# Create build dir
cmake_build_dir="builds/${profile}.${compiler}"
ln -nfs $cmake_build_dir build

# Write active config
(
    echo "profile=$profile"
    echo "compiler=$compiler"
    echo "cmake_build_dir=$cmake_build_dir"
) >./.active_cfg.sh

# Check for git_cached_only mode, stash unstaged changes
if [[ $git_cached_only == 1 ]]; then
    export GIT_DIR=$(git rev-parse --git-dir)
    if [[ -s ${GIT_DIR}/unstaged.diff ]]; then
        echo "Error: pre-existing non-zero unstaged.diff file, aborting"
        exit 1
    fi
    git diff --color=never >${GIT_DIR}/unstaged.diff
    # Add untracked files
    (for file in $(git ls-files --others --exclude-standard); do
        git diff --color=never --no-index /dev/null $file || true
    done) >>${GIT_DIR}/unstaged.diff
    if [[ -s ${GIT_DIR}/unstaged.diff ]]; then
        git apply -R ${GIT_DIR}/unstaged.diff
        trap "git apply ${GIT_DIR}/unstaged.diff && rm ${GIT_DIR}/unstaged.diff || true" 0
    fi
fi

rv=0
# Configure
if [[ ! -e $cmake_build_dir || $do_configure == 1 || ! -e $cmake_build_dir/build.ninja ]]; then
    echo "+ cmake --preset $profile.$compiler --no-warn-unused-cli $cfg_flags"
    cmake --preset $profile.$compiler --no-warn-unused-cli $cfg_flags
    rv=$(($rv || $?))
fi

# Help
function help {
    echo "$script_name cfg | configure"
    echo "$script_name b | build [target]"
    echo "$script_name r | run"
    echo "$script_name c | check"
    echo "$script_name t | test"
    echo "Options:"
    echo "  \$compile    Set the compiler with env var. Current=$compiler"
    echo "  \$profile    Set the build profile with env var. Current=$profile"
    echo "  --cfg        Run the configure step first"
    echo "  --sanitize   Build/Run with address sanitizer"
}

# Sub-comamnds
if [[ $mode == "help" ]]; then
    help
    exit 1
fi

if [[ $target != "" ]]; then
    flags="$flags -t $target"
fi

# build
if [[ $mode == "build" || $mode == "run" || $mode == "test" ]]; then
    bash -c "cmake --build ${cmake_build_dir} ${flags} $MAKEFLAGS $PIPE_COLORPATH; exit \${PIPESTATUS[0]}"
    rv=$(($rv || $?))
fi

if [[ $mode == "build" ]]; then
    if [[ $target == "" ]]; then
        echo "Built all targets:"
        ninja -C build -t targets all | grep CXX_EXECUTABLE_LINKER_ | grep -v '\.cmake' | cut -d: -f1 | sed "s,^,  ./${cmake_build_dir}/,"
    else
        echo "  Built ${cmake_build_dir}/$target"
    fi
    rv=$(($rv || $?))
fi

if [[ $mode == "install" ]]; then
    ninja -C build install
    echo " Installed to ./install/bin"
    rv=$(($rv || $?))
fi

# Check
if [[ $mode == "check" ]]; then
    find src -type f | xargs clang-format -i
    find src -type f | xargs clang-tidy -format-style=file -header-filter=. -p ${cmake_build_dir}
    rv=$(($rv || $?))
fi

# Run
if [[ $mode == "run" ]]; then
    exec $cmake_build_dir/$target "${run_args[@]}"
    rv=$(($rv || $?))
fi

# Test
if [[ $mode == "test" ]]; then
    if [[ "${test_flags}" != "" ]]; then
        test_flags="-R ${test_flags}"
        echo "Running with test flags ${test_flags}"
    fi
    bash -c "ctest ${test_flags} --output-on-failure --test-dir ${cmake_build_dir} $PIPE_COLORPATH; exit \${PIPESTATUS[0]}"
    rv=$(($rv || $?))
fi

# Timing
end_time=$(date +%s)
dur=$(($end_time-$start_time))
if [[ $dur -gt 0 ]]; then
  echo >&2 "Time : $dur seconds"
fi

exit $rv
