#!/bin/bash

PATH=$PATH:$(dirname ${BASH_SOURCE})
top=$(find-root .active_cfg.sh)

if [[ "$top" != "" ]]; then
  cd $top
  source $top/.active_cfg.sh
  echo -n -e "+ ninja -C $cmake_build_dir "$@"| colorpath\n\x1b[1A"
  exec ninja -C $cmake_build_dir "$@" | colorpath
else
  echo -n -e "+ ninja "$@"| colorpath\n\x1b[1A"
  exec ninja "$@" | colorpath
fi
