#!/bin/bash

PATH=$PATH:$(dirname ${BASH_SOURCE})
top=$(find-root .active_cfg.sh)

if [[ "$top" != "" ]]; then
  cd $top
  source $top/.active_cfg.sh
  exec ninja -C $cmake_build_dir "$@" | colorpath
else
  exec ninja "$@" | colorpath
fi
